#! /bin/sh

sxhkd &
dunst &
feh --bg-scale ~/Pictures/wallpaper/6e93a5_7407210.jpg &
polybar main &
picom -b &
xsetroot -cursor_name left_ptr &
keepassxc &

# settings
bspc wm --reorder-monitors DisplayPort-0 HDMI-A-0
bspc monitor HDMI-A-0 -d 四 五
bspc monitor DisplayPort-0 -d 一 二 三 

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false

bspc rule -a Screenkey          manage=off
bspc rule -a Pavucontrol        state=floating

# border & gap
bspc config top_padding         -4
bspc config left_padding        2
bspc config right_padding       2
bspc config bottom_padding      2

bspc config border_width        2
bspc config window_gap          4

# theming
bspc config focused_border_color "#957FB8"
